name: prima-motor-pos-backend

services:
  pm-pocketbase:
    image: nxtgencat/pocketbase:latest
    container_name: pm-pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pocketbase/pb_data
      - ./pb_hooks:/pocketbase/pb_hooks
      - ./pb_migrations:/pocketbase/pb_migrations
    networks:
      - pm-network

  pm-laravel-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pm-laravel-api
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./pb_data:/var/www/html/pb_data
      - ./storage:/var/www/html/storage
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/pb_data/data.db
    networks:
      - pm-network

networks:
  pm-network:
    driver: bridge
